package travis

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/shuheiktgw/go-travis"
)

// Provider returns a *schema.Provider.
func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"api_base_url": {
				Type:        schema.TypeString,
				Optional:    true,
				DefaultFunc: schema.EnvDefaultFunc("TRAVIS_API_BASE_URL", travis.ApiComUrl),
				Description: "the base URL for API request",
			},
			"token": {
				Type:        schema.TypeString,
				Optional:    true,
				DefaultFunc: schema.EnvDefaultFunc("TRAVIS_TOKEN", ""),
				Description: "an API access token generated by the Travis CI command line client: `travis token`",
			},
		},
		ResourcesMap: map[string]*schema.Resource{
			"travis_env_var":  resourceEnvVar(),
			"travis_key_pair": resourceKeyPair(),
		},
		ConfigureFunc: func(d *schema.ResourceData) (interface{}, error) {
			return NewClient(
				d.Get("api_base_url").(string),
				d.Get("token").(string),
			), nil
		},
	}
}
