name: release
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.14.x'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Go Modules
      run: go mod download
    - name: Build
      uses: izumin5210/action-go-crossbuild@releases/v1
    - name: Release Drafter
      id: release_drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Assets
      uses: bgpat/release-asset-action@master
      with:
        pattern: "dist/*"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-id: ${{ steps.release_drafter.outputs.id }}
        allow-overwrite: true
