name: renovate-config-validator
on:
  pull_request:
    paths:
      - renovate.json
      - renovate.json5
      - .github/renovate.json
      - .github/renovate.json5
      - .renovaterc
      - .renovaterc.json
      - .renovaterc.json5
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
