name: test
on:
  push:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/**'
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Version
        id: go-version
        run: echo "::set-output name=version::$(cat .go-version)"
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - run: go test ./...
        env:
          TF_ACC: "true"
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          TRAVIS_REPO_SLUG: ${{ secrets.TRAVIS_REPO_SLUG }}
